### ISSUE TITLE
Attribute "progress" conflicts with "progress" attribute from ConstraintLayout v.2.0.0-beta5

### ISSUE THREAD

**Issue by roudyirany** [GuilhE/android-circular-progress-view#17]
When compiling a project with both this library and ConstraintLayout present, I get the following error:
`AAPT: error: duplicate value for resource 'attr/progress' with config ''.`

**Comment by GuilhE** [comment]
Hello, I've updated `sample module` with

`    implementation 'com.android.support.constraint:constraint-layout:2.0.0-beta5'`

and it worked with no exception:

> Executing tasks: [:sample:assembleDebug] in project .../android-circular-progress-view

> > Task :circular-progress-view:preBuild UP-TO-DATE
> > Task :circular-progress-view:preDebugBuild UP-TO-DATE
> > Task :circular-progress-view:compileDebugAidl NO-SOURCE
> > Task :circular-progress-view:compileDebugRenderscript NO-SOURCE
> > Task :circular-progress-view:generateDebugBuildConfig
> > Task :circular-progress-view:generateDebugResValues
> > Task :circular-progress-view:generateDebugResources
> > Task :circular-progress-view:packageDebugResources
> > Task :sample:preBuild UP-TO-DATE
> > Task :sample:preDebugBuild UP-TO-DATE
> > Task :sample:compileDebugAidl NO-SOURCE
> > Task :circular-progress-view:packageDebugRenderscript NO-SOURCE
> > Task :sample:compileDebugRenderscript NO-SOURCE
> > Task :sample:generateDebugBuildConfig
> > Task :sample:prepareLintJar
> > Task :circular-progress-view:javaPreCompileDebug
> > Task :sample:prepareLintJarForPublish
> > Task :sample:generateDebugSources
> > Task :sample:dataBindingExportBuildInfoDebug
> > Task :circular-progress-view:processDebugManifest
> > Task :sample:dataBindingMergeDependencyArtifactsDebug
> > Task :sample:generateDebugResValues
> > Task :sample:dataBindingExportFeaturePackageIdsDebug
> > Task :sample:generateDebugResources
> > Task :sample:dataBindingMergeGenClassesDebug
> > Task :sample:mainApkListPersistenceDebug
> > Task :circular-progress-view:extractDeepLinksDebug
> > Task :sample:createDebugCompatibleScreenManifests
> > Task :sample:extractDeepLinksDebug
> > Task :sample:processDebugManifest
> > Task :circular-progress-view:compileDebugLibraryResources
> > Task :circular-progress-view:mergeDebugShaders
> > Task :circular-progress-view:compileDebugShaders
> > Task :circular-progress-view:generateDebugAssets
> > Task :circular-progress-view:packageDebugAssets
> > Task :sample:mergeDebugShaders
> > Task :sample:compileDebugShaders
> > Task :sample:generateDebugAssets
> > Task :sample:mergeDebugAssets
> > Task :circular-progress-view:processDebugJavaRes NO-SOURCE
> > Task :circular-progress-view:parseDebugLocalResources
> > Task :sample:processDebugJavaRes NO-SOURCE
> > Task :sample:checkDebugDuplicateClasses
> > Task :sample:desugarDebugFileDependencies
> > Task :sample:mergeDebugResources
> > Task :circular-progress-view:bundleLibResDebug
> > Task :circular-progress-view:generateDebugRFile
> > Task :sample:mergeExtDexDebug
> > Task :circular-progress-view:compileDebugJavaWithJavac
> > Task :sample:dataBindingGenBaseClassesDebug
> > Task :sample:processDebugResources
> > Task :circular-progress-view:mergeDebugJniLibFolders
> > Task :circular-progress-view:bundleLibCompileDebug
> > Task :circular-progress-view:mergeDebugNativeLibs
> > Task :circular-progress-view:bundleLibRuntimeDebug
> > Task :circular-progress-view:stripDebugDebugSymbols
> > Task :circular-progress-view:copyDebugJniLibsProjectOnly
> > Task :sample:mergeDebugJniLibFolders
> > Task :sample:validateSigningDebug
> > Task :sample:javaPreCompileDebug
> > Task :sample:compileDebugJavaWithJavac
> > Task :sample:compileDebugSources
> > Task :sample:mergeDebugNativeLibs
> > Task :sample:dexBuilderDebug
> > Task :sample:mergeDebugJavaResource
> > Task :sample:stripDebugDebugSymbols
> > Task :sample:mergeDexDebug
> > Task :sample:packageDebug
> > Task :sample:assembleDebug
> 
> BUILD SUCCESSFUL in 1m 30s
> 51 actionable tasks: 51 executed

and it runs:

```
10:32	Executing tasks: [:sample:assembleDebug] in project .../android-circular-progress-view
10:33	Gradle build finished in 1 m 31 s 218 ms
10:33	Install successfully finished in 2 s 600 ms.

```

**Comment by roudyirany** [comment]
> Are you using the latest version?
Yeah, I am. Eventually, I just opted to downgrade ConstraintLayout to v.1.1.3 for the attributes to stop conflicting.

**Comment by GuilhE** [comment]
Just tested importing into another project with constraints at beta5 and no collision - build successful.
Can you share the console output of the error?

**Comment by roudyirany** [comment]
This is the console output I get:
`Executing tasks: [clean, :app:assembleStagingDebug] in project /Users/roudyirany/project-android

Configuration on demand is an incubating feature.

> Configure project :app
WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Task :clean
> Task :app:clean
> Task :app:copyResDirectoryToClasses
> Task :app:preBuild
> Task :app:preStagingDebugBuild
> Task :app:compileStagingDebugAidl NO-SOURCE
> Task :app:compileStagingDebugRenderscript NO-SOURCE
> Task :app:generateStagingDebugBuildConfig
> Task :app:mergeStagingDebugShaders
> Task :app:compileStagingDebugShaders NO-SOURCE
> Task :app:generateStagingDebugAssets UP-TO-DATE
> Task :app:mergeStagingDebugAssets

> Task :app:processStagingDebugGoogleServices
Parsing json file: /Users/roudyirany/project-android/app/google-services.json

> Task :app:createStagingDebugCompatibleScreenManifests
> Task :app:extractDeepLinksStagingDebug

> Task :app:processStagingDebugManifest
/Users/roudyirany/project-android/app/src/main/AndroidManifest.xml:8:3-162:17 Warning:
	application@tools:label was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present

> Task :app:fabricGenerateResourcesStagingDebug
> Task :app:generateStagingDebugResValues
> Task :app:generateStagingDebugResources
> Task :app:javaPreCompileStagingDebug

> Task :app:mergeStagingDebugResources FAILED
AGPBI: {"kind":"error","text":"Android resource compilation failed","sources":[{"file":"/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml","position":{"startLine":7430}}],"original":"/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml:7431: AAPT: error: duplicate value for resource 'attr/progress' with config ''.\n    ","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Android resource compilation failed","sources":[{"file":"/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml","position":{"startLine":7430}}],"original":"/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml:7431: AAPT: error: resource previously defined here.\n    ","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Android resource compilation failed","sources":[{"file":"/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml"}],"original":"/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.\n    ","tool":"AAPT"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeStagingDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource compilation failed
     /Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml:7431: AAPT: error: duplicate value for resource 'attr/progress' with config ''.
         
     /Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml:7431: AAPT: error: resource previously defined here.
         
     /Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.
         

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeStagingDebugResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
	at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:354)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:142)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.access$000(DefaultAsyncWorkTracker.java:34)
	at org.gradle.internal.work.DefaultAsyncWorkTracker$1.run(DefaultAsyncWorkTracker.java:106)
	at org.gradle.internal.Factories$1.create(Factories.java:26)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:260)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutProjectLock(DefaultWorkerLeaseService.java:171)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutProjectLock(DefaultWorkerLeaseService.java:165)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withoutProjectLock(StopShieldingWorkerLeaseService.java:95)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:102)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForAll(DefaultAsyncWorkTracker.java:80)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:68)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:576)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:63)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
	... 30 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml:7431: AAPT: error: duplicate value for resource 'attr/progress' with config ''.
    
/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml:7431: AAPT: error: resource previously defined here.
    
/Users/roudyirany/project-android/app/build/intermediates/incremental/mergeStagingDebugResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.
    
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create(Aapt2Exception.kt:45)
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create$default(Aapt2Exception.kt:39)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:195)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteCompileException(Aapt2ErrorUtils.kt:87)
	at com.android.build.gradle.internal.res.Aapt2CompileRunnable$run$1.invoke(Aapt2CompileRunnable.kt:40)
	at com.android.build.gradle.internal.res.Aapt2CompileRunnable$run$1.invoke(Aapt2CompileRunnable.kt:29)
	at com.android.build.gradle.internal.services.Aapt2Daemon.useAaptDaemon(Aapt2DaemonBuildService.kt:83)
	at com.android.build.gradle.internal.services.Aapt2Daemon.useAaptDaemon$default(Aapt2DaemonBuildService.kt:81)
	at com.android.build.gradle.internal.res.Aapt2CompileRunnable.run(Aapt2CompileRunnable.kt:35)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:242)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:50)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:59)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:53)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	... 3 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
14 actionable tasks: 14 executed`
